<?php

namespace Database\Seeders;

use App\Models\SubCategory;
use App\Models\Template;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            // === PERNIKAHAN - Akad Nikah ===
            [
                'sub_category' => 'akad-nikah',
                'name' => 'Elegant Rose',
                'slug' => 'elegant-rose',
                'description' => 'Template undangan akad nikah dengan desain elegant rose gold yang mewah dan modern. Cocok untuk acara pernikahan yang formal dan mewah.',
                'preview_image' => null, // TODO: Add preview image
                'demo_url' => 'https://demo.lemparsini.com/elegant-rose',
                'component_path' => 'templates/wedding/ElegantRose',
                'price' => 0,
                'is_free' => true,
                'is_premium' => false,
                'features' => [
                    'Video background',
                    'Music player',
                    'Countdown timer',
                    'Photo gallery (10 photos)',
                    'Google Maps integration',
                    'RSVP form',
                    'Guest wishes',
                    'Share to social media',
                ],
                'customizable_fields' => [
                    'bride_name',
                    'groom_name',
                    'event_date',
                    'event_time',
                    'event_location',
                    'event_address',
                    'photos',
                    'background_music',
                    'primary_color',
                    'opening_text',
                    'closing_text',
                ],
                'status' => 'published',
                'views_count' => 1250,
                'usage_count' => 89,
            ],
            [
                'sub_category' => 'akad-nikah',
                'name' => 'Classic White',
                'slug' => 'classic-white',
                'description' => 'Template minimalis dengan tema putih klasik. Simple, elegant, dan timeless untuk acara akad nikah yang sakral.',
                'preview_image' => null, // TODO: Add preview image
                'demo_url' => 'https://demo.lemparsini.com/classic-white',
                'component_path' => 'templates/wedding/ClassicWhite',
                'price' => 99000,
                'is_free' => false,
                'is_premium' => true,
                'features' => [
                    'Parallax scrolling',
                    'Music player with playlist',
                    'Countdown timer',
                    'Photo gallery (unlimited)',
                    'Video embed (YouTube/Instagram)',
                    'Google Maps integration',
                    'RSVP form with meal preference',
                    'Guest wishes with moderation',
                    'Digital envelope (cashless gift)',
                    'Guest attendance tracking',
                    'WhatsApp broadcast integration',
                ],
                'customizable_fields' => [
                    'bride_name',
                    'bride_fullname',
                    'bride_father',
                    'bride_mother',
                    'groom_name',
                    'groom_fullname',
                    'groom_father',
                    'groom_mother',
                    'event_date',
                    'event_time',
                    'event_location',
                    'event_address',
                    'photos',
                    'videos',
                    'background_music',
                    'color_theme',
                    'font_style',
                    'opening_text',
                    'quran_verse',
                    'closing_text',
                    'bank_accounts',
                ],
                'status' => 'published',
                'views_count' => 2340,
                'usage_count' => 156,
            ],
            [
                'sub_category' => 'akad-nikah',
                'name' => 'Golden Luxury',
                'slug' => 'golden-luxury',
                'description' => 'Template mewah dengan aksen gold dan ornamen islami. Cocok untuk pernikahan adat dengan nuansa elegan dan glamour.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/golden-luxury',
                'component_path' => 'templates/wedding/GoldenLuxury',
                'price' => 199000,
                'is_free' => false,
                'is_premium' => true,
                'features' => [
                    '3D animation intro',
                    'Music player with autoplay',
                    'Countdown to multiple events',
                    'Photo & video gallery (unlimited)',
                    'Instagram feed integration',
                    'Google Maps + Waze integration',
                    'RSVP with guest count',
                    'Guest wishes with approval',
                    'Digital envelope (multiple banks)',
                    'Love story timeline',
                    'Wedding gift registry',
                    'QR code for easy access',
                    'Custom domain support',
                ],
                'customizable_fields' => [
                    'bride_name',
                    'bride_fullname',
                    'bride_nickname',
                    'bride_father',
                    'bride_mother',
                    'bride_instagram',
                    'groom_name',
                    'groom_fullname',
                    'groom_nickname',
                    'groom_father',
                    'groom_mother',
                    'groom_instagram',
                    'event_date',
                    'event_time',
                    'akad_location',
                    'akad_address',
                    'resepsi_location',
                    'resepsi_address',
                    'photos',
                    'videos',
                    'background_music',
                    'color_scheme',
                    'font_pairing',
                    'opening_text',
                    'quran_verse',
                    'love_story',
                    'closing_text',
                    'bank_accounts',
                    'gift_registry',
                ],
                'status' => 'published',
                'views_count' => 3890,
                'usage_count' => 234,
            ],

            // === PERNIKAHAN - Resepsi ===
            [
                'sub_category' => 'resepsi',
                'name' => 'Modern Floral',
                'slug' => 'modern-floral',
                'description' => 'Template resepsi dengan desain floral modern yang fresh dan colorful. Cocok untuk resepsi outdoor atau garden party.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/modern-floral',
                'component_path' => 'templates/wedding/ModernFloral',
                'price' => 0,
                'is_free' => true,
                'is_premium' => false,
                'features' => [
                    'Animated flower elements',
                    'Music player',
                    'Countdown timer',
                    'Photo gallery (15 photos)',
                    'Google Maps',
                    'RSVP form',
                    'Guest book',
                ],
                'customizable_fields' => [
                    'bride_name',
                    'groom_name',
                    'event_date',
                    'event_time',
                    'venue_name',
                    'venue_address',
                    'photos',
                    'music',
                    'theme_color',
                ],
                'status' => 'published',
                'views_count' => 980,
                'usage_count' => 67,
            ],
            [
                'sub_category' => 'resepsi',
                'name' => 'Rustic Charm',
                'slug' => 'rustic-charm',
                'description' => 'Template dengan tema rustic yang hangat dan natural. Perfect untuk resepsi outdoor dengan konsep vintage.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/rustic-charm',
                'component_path' => 'templates/wedding/RusticCharm',
                'price' => 99000,
                'is_free' => false,
                'is_premium' => true,
                'features' => [
                    'Vintage animations',
                    'Music playlist',
                    'Countdown with timezone',
                    'Photo gallery (unlimited)',
                    'Video montage',
                    'Location maps',
                    'RSVP with dietary needs',
                    'Guest messages',
                    'Digital angpao',
                    'Accommodation info',
                ],
                'customizable_fields' => [
                    'couple_names',
                    'event_details',
                    'venues',
                    'schedules',
                    'gallery',
                    'videos',
                    'music',
                    'colors',
                    'texts',
                    'gift_options',
                ],
                'status' => 'published',
                'views_count' => 1560,
                'usage_count' => 92,
            ],

            // === PERNIKAHAN - Intimate Wedding ===
            [
                'sub_category' => 'intimate-wedding',
                'name' => 'Simple Elegance',
                'slug' => 'simple-elegance',
                'description' => 'Template minimalis untuk intimate wedding. Simple namun tetap elegant dan memorable.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/simple-elegance',
                'component_path' => 'templates/wedding/SimpleElegance',
                'price' => 0,
                'is_free' => true,
                'is_premium' => false,
                'features' => [
                    'Clean minimal design',
                    'Background music',
                    'Event countdown',
                    'Photo gallery (8 photos)',
                    'Location link',
                    'RSVP confirmation',
                ],
                'customizable_fields' => [
                    'names',
                    'date',
                    'location',
                    'photos',
                    'message',
                ],
                'status' => 'published',
                'views_count' => 720,
                'usage_count' => 45,
            ],

            // === ULANG TAHUN - Anak ===
            [
                'sub_category' => 'ulang-tahun-anak',
                'name' => 'Happy Birthday Kids',
                'slug' => 'happy-birthday-kids',
                'description' => 'Template colorful dan fun untuk ulang tahun anak. Dengan karakter lucu dan animasi ceria.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/happy-birthday-kids',
                'component_path' => 'templates/birthday/HappyBirthdayKids',
                'price' => 0,
                'is_free' => true,
                'is_premium' => false,
                'features' => [
                    'Cartoon animations',
                    'Fun background music',
                    'Balloon effects',
                    'Photo collage',
                    'Location map',
                    'RSVP counter',
                    'Gift wishlist',
                ],
                'customizable_fields' => [
                    'child_name',
                    'age',
                    'party_theme',
                    'date_time',
                    'venue',
                    'photos',
                    'color_theme',
                ],
                'status' => 'published',
                'views_count' => 650,
                'usage_count' => 38,
            ],

            // === ULANG TAHUN - Sweet Seventeen ===
            [
                'sub_category' => 'sweet-seventeen',
                'name' => 'Sweet & Chic',
                'slug' => 'sweet-and-chic',
                'description' => 'Template trendy untuk sweet seventeen. Modern, stylish, dan Instagram-worthy.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/sweet-and-chic',
                'component_path' => 'templates/birthday/SweetAndChic',
                'price' => 99000,
                'is_free' => false,
                'is_premium' => true,
                'features' => [
                    'Modern animations',
                    'Spotify integration',
                    'Instagram filter',
                    'Photo booth gallery',
                    'Video montage',
                    'Location details',
                    'RSVP form',
                    'Dress code info',
                    'Digital gift',
                ],
                'customizable_fields' => [
                    'birthday_girl_name',
                    'event_date',
                    'venue',
                    'theme',
                    'photos',
                    'videos',
                    'music_playlist',
                    'color_palette',
                    'dress_code',
                ],
                'status' => 'published',
                'views_count' => 1120,
                'usage_count' => 71,
            ],

            // === ACARA KEAGAMAAN - Aqiqah ===
            [
                'sub_category' => 'aqiqah',
                'name' => 'Islamic Aqiqah',
                'slug' => 'islamic-aqiqah',
                'description' => 'Template aqiqah dengan ornamen islami yang indah. Cocok untuk acara aqiqah yang khidmat dan berkesan.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/islamic-aqiqah',
                'component_path' => 'templates/religious/IslamicAqiqah',
                'price' => 0,
                'is_free' => true,
                'is_premium' => false,
                'features' => [
                    'Islamic ornaments',
                    'Quranic verses',
                    'Arabic calligraphy',
                    'Baby photo showcase',
                    'Event details',
                    'Location map',
                    'RSVP confirmation',
                ],
                'customizable_fields' => [
                    'baby_name',
                    'baby_gender',
                    'parents_names',
                    'birth_date',
                    'aqiqah_date',
                    'location',
                    'photos',
                    'quran_verse',
                    'doa',
                ],
                'status' => 'published',
                'views_count' => 890,
                'usage_count' => 56,
            ],
            [
                'sub_category' => 'aqiqah',
                'name' => 'Gold Aqiqah',
                'slug' => 'gold-aqiqah',
                'description' => 'Template aqiqah premium dengan aksen gold yang mewah dan elegant.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/gold-aqiqah',
                'component_path' => 'templates/religious/GoldAqiqah',
                'price' => 99000,
                'is_free' => false,
                'is_premium' => true,
                'features' => [
                    'Premium gold design',
                    'Islamic patterns',
                    'Quranic recitation',
                    'Photo & video gallery',
                    'Family tree',
                    'Multiple locations',
                    'RSVP with guest count',
                    'Doa & hadith',
                    'Digital envelope',
                ],
                'customizable_fields' => [
                    'baby_fullname',
                    'baby_nickname',
                    'baby_gender',
                    'parents_fullnames',
                    'grandparents',
                    'birth_info',
                    'aqiqah_schedule',
                    'venues',
                    'photos',
                    'videos',
                    'quran_verses',
                    'duas',
                    'bank_details',
                ],
                'status' => 'published',
                'views_count' => 1450,
                'usage_count' => 89,
            ],

            // === ACARA KEAGAMAAN - Khitanan ===
            [
                'sub_category' => 'khitanan',
                'name' => 'Khitan Celebration',
                'slug' => 'khitan-celebration',
                'description' => 'Template khitanan/sunatan dengan desain islami yang ceria dan bermakna.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/khitan-celebration',
                'component_path' => 'templates/religious/KhitanCelebration',
                'price' => 0,
                'is_free' => true,
                'is_premium' => false,
                'features' => [
                    'Islamic theme',
                    'Music player',
                    'Photo gallery',
                    'Event schedule',
                    'Location info',
                    'RSVP form',
                ],
                'customizable_fields' => [
                    'child_name',
                    'age',
                    'parents_names',
                    'event_date',
                    'location',
                    'photos',
                    'message',
                ],
                'status' => 'published',
                'views_count' => 560,
                'usage_count' => 34,
            ],

            // === CORPORATE EVENTS - Seminar ===
            [
                'sub_category' => 'seminar-workshop',
                'name' => 'Professional Seminar',
                'slug' => 'professional-seminar',
                'description' => 'Template professional untuk seminar dan workshop. Clean, modern, dan business-oriented.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/professional-seminar',
                'component_path' => 'templates/corporate/ProfessionalSeminar',
                'price' => 99000,
                'is_free' => false,
                'is_premium' => true,
                'features' => [
                    'Corporate design',
                    'Agenda timeline',
                    'Speaker profiles',
                    'Venue information',
                    'Registration form',
                    'QR code check-in',
                    'Certificate info',
                    'Sponsor showcase',
                ],
                'customizable_fields' => [
                    'event_title',
                    'organizer',
                    'date_time',
                    'venue',
                    'speakers',
                    'agenda',
                    'registration_link',
                    'sponsors',
                    'contact_info',
                ],
                'status' => 'published',
                'views_count' => 780,
                'usage_count' => 42,
            ],

            // === CORPORATE EVENTS - Grand Opening ===
            [
                'sub_category' => 'grand-opening',
                'name' => 'Grand Opening Celebration',
                'slug' => 'grand-opening-celebration',
                'description' => 'Template untuk grand opening usaha. Meriah, professional, dan eye-catching.',
                'preview_image' => null,
                'demo_url' => 'https://demo.lemparsini.com/grand-opening-celebration',
                'component_path' => 'templates/corporate/GrandOpeningCelebration',
                'price' => 99000,
                'is_free' => false,
                'is_premium' => true,
                'features' => [
                    'Festive animations',
                    'Business info',
                    'Photo gallery',
                    'Promo highlights',
                    'Location & directions',
                    'RSVP tracking',
                    'Social media links',
                ],
                'customizable_fields' => [
                    'business_name',
                    'business_type',
                    'opening_date',
                    'location',
                    'photos',
                    'promotions',
                    'social_media',
                    'contact',
                ],
                'status' => 'published',
                'views_count' => 920,
                'usage_count' => 58,
            ],
        ];

        foreach ($templates as $templateData) {
            // Get sub_category by slug
            $subCategorySlug = $templateData['sub_category'];
            unset($templateData['sub_category']);

            $subCategory = SubCategory::where('slug', $subCategorySlug)->first();

            if ($subCategory) {
                // Set sub_category_id
                // Note: Don't json_encode features/customizable_fields - Laravel's array cast handles it
                $templateData['sub_category_id'] = $subCategory->id;

                Template::create($templateData);
            }
        }
    }
}
